# Bun 配置文件
[install]
# 使用淘宝 npm 镜像源
registry = "https://registry.npmmirror.com/"

# 使用更快的包解析
cache = true
exact = false

# 锁定文件格式
lockfile = true

# 开发依赖处理
dev = true

[run]
# 启用热重载
watch = true

# 监听文件变化时忽略的路径
watchIgnore = ["node_modules", "dist", ".git", "*.log", "logs", "backup"]

# 监听的文件扩展名
watchExtensions = ["ts", "js", "json", "yaml", "toml"]

# 环境变量文件 (按优先级加载)
env = [".env.local", ".env"]
